---
- name: Install plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    url_username: admin
    url_password: admin
    url: http://localhost:8080

- name: Install plugin
  jenkins_plugin:
    name: blue-ocean

- name: Initiate the fact
    set_fact:
    jenkins_restart_required: yes
